// Plain-language conclusions generated by rules over the computed metrics.
// Deterministic and verifiable — no AI, no guessing. Each conclusion has a
// severity so the UI can highlight what needs attention.

export type Level = 'good' | 'warn' | 'bad';
export interface Conclusion {
  level: Level;
  title: string;
  detail: string;
}

function money(cents: bigint): string {
  const n = Number(cents) / 100;
  const abs = Math.abs(n);
  const s = abs >= 1_000_000 ? `${(abs / 1_000_000).toFixed(1)}M` : abs >= 1000 ? `${Math.round(abs / 1000)}k` : abs.toFixed(0);
  return `${n < 0 ? '-' : ''}$${s}`;
}

export interface ConclusionInput {
  maxPosTicker: string;
  maxPosPct: number;
  maxClassName: string;
  maxClassPct: number;
  classCount: number;
  usdPct: number;
  cedear?: { winRatePct: number; realizedCents: bigint };
  arg?: { winRatePct: number; realizedCents: bigint };
  winRatePct: number;
  totalSales: number;
  riskReward: number | null;
  costsPctOfVolume: number;
  totalPnlCents: bigint;
  returnPct: number | null;
  holdingsCount: number;
}

const order: Record<Level, number> = { bad: 0, warn: 1, good: 2 };

/** Conclusions computable synchronously from the portfolio's own data. */
export function coreConclusions(i: ConclusionInput): Conclusion[] {
  const out: Conclusion[] = [];

  // Concentration
  if (i.maxPosPct > 40) {
    out.push({ level: 'bad', title: 'Cartera muy concentrada', detail: `${i.maxPosTicker} es el ${i.maxPosPct.toFixed(0)}% de tu cartera. Una caída fuerte de ese activo te pega de lleno — conviene diversificar.` });
  } else if (i.maxPosPct > 20) {
    out.push({ level: 'warn', title: 'Concentración a vigilar', detail: `${i.maxPosTicker} pesa ${i.maxPosPct.toFixed(0)}% (umbral recomendado 20%).` });
  } else {
    out.push({ level: 'good', title: 'Concentración saludable', detail: `Ningún activo supera el 20% (máximo: ${i.maxPosTicker} ${i.maxPosPct.toFixed(0)}%).` });
  }

  // Currency / FX protection
  if (i.usdPct < 30) {
    out.push({ level: 'warn', title: 'Poco protegido al tipo de cambio', detail: `Solo el ${i.usdPct.toFixed(0)}% de tu cartera sigue al dólar. Ante una devaluación del peso, tu patrimonio en USD cae.` });
  } else if (i.usdPct > 70) {
    out.push({ level: 'good', title: 'Bien dolarizado', detail: `El ${i.usdPct.toFixed(0)}% sigue al dólar: estás cubierto ante una devaluación.` });
  } else {
    out.push({ level: 'good', title: 'Balance de moneda razonable', detail: `${i.usdPct.toFixed(0)}% dolarizado / ${(100 - i.usdPct).toFixed(0)}% en pesos.` });
  }

  // Class diversification
  if (i.maxClassPct > 70) {
    out.push({ level: 'warn', title: 'Poca diversificación por tipo de activo', detail: `${i.maxClassName} concentra el ${i.maxClassPct.toFixed(0)}% de tu cartera.` });
  }

  // Behavior: CEDEAR vs ARG pattern
  if (i.cedear && i.arg && i.cedear.realizedCents > 0n && i.arg.realizedCents < 0n) {
    out.push({ level: 'warn', title: 'Tu fuerte son los CEDEARs, no las acciones argentinas', detail: `En CEDEARs ganás el ${i.cedear.winRatePct.toFixed(0)}% de las veces (${money(i.cedear.realizedCents)}); en acciones ARG, ${i.arg.winRatePct.toFixed(0)}% (${money(i.arg.realizedCents)}). Los datos sugieren enfocar tu trading donde tenés ventaja.` });
  }

  // Win rate / risk-reward
  if (i.totalSales >= 5) {
    if (i.winRatePct < 40 && (i.riskReward ?? 0) >= 1.5) {
      out.push({ level: 'good', title: 'Pocas aciertan, pero las ganadoras compensan', detail: `Win rate ${i.winRatePct.toFixed(0)}%, pero ganás ${i.riskReward!.toFixed(1)}x de lo que perdés: dejás correr ganadoras y cortás pérdidas.` });
    } else if (i.winRatePct < 40 && (i.riskReward ?? 0) < 1) {
      out.push({ level: 'bad', title: 'Patrón de trading a revisar', detail: `Acertás solo el ${i.winRatePct.toFixed(0)}% y, cuando ganás, ganás menos de lo que perdés. Estás perdiendo por ambos lados.` });
    }
  }

  // Costs
  if (i.costsPctOfVolume > 0 && i.costsPctOfVolume < 1) {
    out.push({ level: 'good', title: 'Costos bajo control', detail: `Comisiones e impuestos son el ${i.costsPctOfVolume.toFixed(2)}% del volumen operado.` });
  } else if (i.costsPctOfVolume >= 1.5) {
    out.push({ level: 'warn', title: 'Costos altos', detail: `Estás pagando ${i.costsPctOfVolume.toFixed(2)}% del volumen en costos: cuidá la frecuencia de operaciones.` });
  }

  // Overall result
  if (i.returnPct != null) {
    if (i.totalPnlCents >= 0n) {
      out.push({ level: 'good', title: 'Resultado positivo', detail: `Ganancia total ${money(i.totalPnlCents)} (${i.returnPct.toFixed(1)}% sobre tu aporte neto).` });
    } else {
      out.push({ level: 'bad', title: 'Resultado negativo', detail: `Pérdida total ${money(i.totalPnlCents)} (${i.returnPct.toFixed(1)}% sobre tu aporte neto).` });
    }
  }

  // Few holdings
  if (i.holdingsCount > 0 && i.holdingsCount < 4) {
    out.push({ level: 'warn', title: 'Pocos activos', detail: `Tenés solo ${i.holdingsCount} posición(es). Más activos (poco correlacionados) reducen el riesgo.` });
  }

  return out.sort((a, b) => order[a.level] - order[b.level]);
}
